### ISSUE TITLE
[KCSG] Cannot add more symbolDef. Maximum amount reached. 

### ISSUE THREAD

**Issue by brucethemoose** [Vanilla-Expanded/VanillaExpandedFramework#2]
The titular error seems to be popping up in modlists quite a bit, see the discussion and logs here:

https://steamcommunity.com/workshop/filedetails/discussion/2023507013/3130541756140048010/?ctp=43#c3487500856968645272

Clearly there is a hard limit to the number of defs here:
https://github.com/Vanilla-Expanded/VanillaExpandedFramework/blob/c7ff86800f73a9f0b92c1c8b2a6a0500760027f6/Source/KCSG/StartupActions.cs#L129

... But how exactly are these defs getting filled? I tried removing all mods with references to `symbolDef` in their xml, and I'm still running into this error:  https://gist.github.com/HugsLibRecordKeeper/e196279892ba087ea4e4e6b09bec7c64#file-output_log-txt-L3950

![Capture](https://user-images.githubusercontent.com/8422224/197423122-7a67c1e7-d358-44ea-b373-42d77ab7c2d1.PNG)

**Comment by KylianB** [comment]
SymbolDefs for vanilla are auto-generated at startup by the framework. The hard limit is vanilla, I'm just preventing it to happen to not cause bigger issues. This is the case since 1.3 (that's why the screenshot you posted show symbols XML file only for the 1.2 version). Something must be messing with it, since I cannot reproduce that with my mod list. Some mods seem to cause the issue, Rimefeller being one of them. Will investigate! If you don't mind, please also try to disable mods and see which is causing it for you.

**Comment by KylianB** [comment]
Should be fixed with the last version, please try and tell me.

**Comment by p0xus** [comment]
Im still getting the error. I just tried removing Rimefeller and still its happening. Might be another mod contributing to it.

**Comment by brucethemoose** [comment]
Yeah the Github fix works for me too. 

>  If you don't mind, please also try to disable mods and see which is causing it for you.

2 mods that pushed my loadout "over the edge" were vanilla outposts expanded and vanilla base generation expanded. Some faction mods like vanilla expanded ancients also seemed to contribute.

**Comment by KylianB** [comment]
We will be pushing the fix to steam as soon as possible, thanks for the report. Closing the issue.
