### ISSUE TITLE
Pawns that spawn on mortars leave map once they run out of ammo

### ISSUE THREAD

**Issue by glencoe2004** [Vanilla-Expanded/VanillaExpandedFramework#63]
No logs because it doesn't throw any errors.

Steps to reproduce:
1. Create a WorldObject with a CustomGenOption layout that includes mortars
2. Go to the resulting map and wait for enemy mortars to run out of ammo
3. Observe as mortar pawns leave map

Also, pawns leaving map seem to not attack colonists.

Pawns leaving the map may or may not be intended behavior. A possible solution could be to add a toggle that makes pawns spawned on mortars patrol the center of the map instead of leaving.

**Comment by KylianB** [comment]
This commit should fix this, I'm now using the same code as vanilla.

**Comment by glencoe2004** [comment]
This doesn't seem to fix the issue unfortunately, pawns will still leave the map once their ammo is exhausted
